USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE TABLE INCIDENT_ACTION_QUEUE AS
SELECT
    CONCAT('ACT_', EVENT_ID) AS ACTION_ID,
    EVENT_ID,
    AGENT_ID,

    CASE
        WHEN ISSUE_TYPE = 'TIMEOUT' AND AUTO_REMEDIATE = 'YES' THEN 'RETRY_WITH_BACKOFF'
        WHEN ISSUE_TYPE = 'PERMISSION' THEN 'VALIDATE_ROLE_AND_GRANTS'
        WHEN ISSUE_TYPE = 'DATA_QUALITY' THEN 'QUARANTINE_INPUT_AND_NOTIFY_OWNER'
        WHEN ISSUE_TYPE = 'UPSTREAM' THEN 'CHECK_UPSTREAM_AGENT'
        ELSE 'MANUAL_REVIEW'
    END AS ACTION_TYPE,

    'OPEN' AS ACTION_STATUS,
    PRIORITY_SCORE AS ACTION_PRIORITY,
    ROOT_CAUSE AS ACTION_REASON,

    CASE
        WHEN AUTO_REMEDIATE = 'YES' THEN 'N'
        ELSE 'Y'
    END AS HUMAN_APPROVAL_REQUIRED,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM AGENT_INCIDENT_PRIORITY;