USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT
    ACTION_ID,
    EVENT_ID,
    AGENT_ID,
    ACTION_TYPE,
    ACTION_STATUS,
    ACTION_PRIORITY,
    HUMAN_APPROVAL_REQUIRED
FROM INCIDENT_ACTION_QUEUE
ORDER BY ACTION_PRIORITY DESC, CREATED_AT DESC;