USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW OBSERVABILITY_KPIS AS
SELECT
    COUNT(*) AS TOTAL_LOGS,
    COUNT_IF(ISSUE_TYPE <> 'SUCCESS') AS FAILED_LOGS,
    ROUND(100.0 * COUNT_IF(ISSUE_TYPE <> 'SUCCESS') / NULLIF(COUNT(*), 0), 2) AS FAILURE_RATE_PCT,
    COUNT_IF(SEVERITY = 'HIGH') AS HIGH_SEVERITY_INCIDENTS
FROM CORTEX_LOG_ENRICHED_PARSED;