USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW INCIDENTS_BY_ISSUE_TYPE AS
SELECT
    ISSUE_TYPE,
    COUNT(*) AS INCIDENT_COUNT
FROM CORTEX_LOG_ENRICHED_PARSED
GROUP BY ISSUE_TYPE
ORDER BY INCIDENT_COUNT DESC, ISSUE_TYPE;