USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW INCIDENTS_BY_SEVERITY AS
SELECT
    SEVERITY,
    COUNT(*) AS INCIDENT_COUNT
FROM CORTEX_LOG_ENRICHED_PARSED
GROUP BY SEVERITY
ORDER BY INCIDENT_COUNT DESC, SEVERITY;