USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW INCIDENT_DETAILS AS
SELECT
    ID,
    LOG_TEXT,
    ISSUE_TYPE,
    SEVERITY,
    ROOT_CAUSE,
    NEXT_STEP
FROM CORTEX_LOG_ENRICHED_PARSED
ORDER BY ID;