USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT * FROM OBSERVABILITY_KPIS;

SELECT * 
FROM INCIDENTS_BY_ISSUE_TYPE
ORDER BY INCIDENT_COUNT DESC, ISSUE_TYPE;

SELECT *
FROM INCIDENTS_BY_SEVERITY
ORDER BY INCIDENT_COUNT DESC, SEVERITY;

SELECT *
FROM INCIDENT_DETAILS
ORDER BY ID;