USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW SNOWWATCH_INCIDENT_QUEUE AS
SELECT
    EVENT_ID,
    AGENT_ID,
    EVENT_TS,
    ISSUE_TYPE,
    SEVERITY,
    ROOT_CAUSE,
    NEXT_STEP,
    AUTO_REMEDIATE,
    CONFIDENCE,
    DIRECTLY_IMPACTED_AGENTS,
    PRIORITY_SCORE
FROM AGENT_INCIDENT_PRIORITY
ORDER BY PRIORITY_SCORE DESC, EVENT_TS DESC;