USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT
    EVENT_ID,
    AGENT_ID,
    ISSUE_TYPE,
    SEVERITY,
    DIRECTLY_IMPACTED_AGENTS,
    AUTO_REMEDIATE,
    PRIORITY_SCORE
FROM SNOWWATCH_INCIDENT_QUEUE;