USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW SNOWWATCH_INCIDENT_DETAILS AS
SELECT
    i.EVENT_ID,
    i.AGENT_RUN_ID,
    i.AGENT_ID,
    r.AGENT_NAME,
    r.AGENT_DOMAIN,
    r.AGENT_OWNER,
    r.BUSINESS_CRITICALITY,
    i.EVENT_TS,
    i.STATUS,
    i.ISSUE_TYPE,
    i.SEVERITY,
    i.ROOT_CAUSE,
    i.NEXT_STEP,
    i.AUTO_REMEDIATE,
    i.CONFIDENCE,
    i.INCIDENT_LABEL,
    e.EVENT_TYPE,
    e.EXEC_TIME_MS,
    e.TOKENS_INPUT,
    e.TOKENS_OUTPUT,
    e.MODEL_NAME,
    e.WAREHOUSE_NAME,
    e.DATABASE_NAME,
    e.SCHEMA_NAME,
    e.OBJECT_NAME,
    e.OBJECT_TYPE,
    e.USER_ROLE,
    e.ERROR_CODE,
    e.ERROR_MESSAGE,
    e.RETRY_COUNT,
    e.LOG_TEXT
FROM AGENT_INCIDENTS_PARSED i
LEFT JOIN AGENT_EVENT_LOGS e
    ON i.EVENT_ID = e.EVENT_ID
LEFT JOIN AGENT_REGISTRY r
    ON i.AGENT_ID = r.AGENT_ID
ORDER BY i.EVENT_TS DESC;