USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT
    EVENT_ID,
    AGENT_ID,
    AGENT_NAME,
    AGENT_DOMAIN,
    AGENT_OWNER,
    BUSINESS_CRITICALITY,
    ISSUE_TYPE,
    SEVERITY,
    OBJECT_NAME,
    ERROR_CODE,
    RETRY_COUNT
FROM SNOWWATCH_INCIDENT_DETAILS
ORDER BY EVENT_TS DESC;