USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SHOW STREAMS LIKE 'AGENT_EVENT_LOGS_STREAM';

SHOW TASKS LIKE 'TASK_REFRESH_AGENT_INCIDENT_ENRICHED';

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TASK_REFRESH_AGENT_INCIDENT_ENRICHED',
    RESULT_LIMIT => 10
));