USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW CORTEX_LOG_ENRICHED_PARSED AS
SELECT
    ID,
    LOG_TEXT,
    STRUCTURED_DIAGNOSIS,

    TRIM(REPLACE(SPLIT_PART(STRUCTURED_DIAGNOSIS, '\n', 1), 'ISSUE_TYPE:', '')) AS ISSUE_TYPE,

    TRIM(REPLACE(SPLIT_PART(STRUCTURED_DIAGNOSIS, '\n', 2), 'SEVERITY:', '')) AS SEVERITY,

    TRIM(REPLACE(SPLIT_PART(STRUCTURED_DIAGNOSIS, '\n', 3), 'ROOT_CAUSE:', '')) AS ROOT_CAUSE,

    TRIM(REPLACE(SPLIT_PART(STRUCTURED_DIAGNOSIS, '\n', 4), 'NEXT_STEP:', '')) AS NEXT_STEP

FROM CORTEX_LOG_ENRICHED;