USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW AGENT_INCIDENTS_PARSED AS
SELECT
    EVENT_ID,
    AGENT_RUN_ID,
    AGENT_ID,
    EVENT_TS,
    STATUS,
    LOG_TEXT,
    AI_DIAGNOSIS,

    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 1), 'ISSUE_TYPE:', '')) AS ISSUE_TYPE,
    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 2), 'SEVERITY:', '')) AS SEVERITY,
    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 3), 'ROOT_CAUSE:', '')) AS ROOT_CAUSE,
    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 4), 'NEXT_STEP:', '')) AS NEXT_STEP,
    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 5), 'AUTO_REMEDIATE:', '')) AS AUTO_REMEDIATE,
    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 6), 'CONFIDENCE:', '')) AS CONFIDENCE,
    TRIM(REPLACE(SPLIT_PART(AI_DIAGNOSIS, '\n', 7), 'INCIDENT_LABEL:', '')) AS INCIDENT_LABEL

FROM AGENT_INCIDENT_ENRICHED;