USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT
    EVENT_ID,
    AGENT_ID,
    STATUS,
    ISSUE_TYPE,
    SEVERITY,
    ROOT_CAUSE,
    NEXT_STEP,
    AUTO_REMEDIATE,
    CONFIDENCE,
    INCIDENT_LABEL
FROM AGENT_INCIDENTS_PARSED
ORDER BY EVENT_ID;