USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW AGENT_DIRECT_IMPACT AS
SELECT
    i.EVENT_ID,
    i.AGENT_ID,
    COUNT(d.CHILD_AGENT_ID) AS DIRECTLY_IMPACTED_AGENTS
FROM AGENT_INCIDENTS_PARSED i
LEFT JOIN AGENT_DEPENDENCIES d
    ON i.AGENT_ID = d.PARENT_AGENT_ID
WHERE i.ISSUE_TYPE <> 'SUCCESS'
GROUP BY i.EVENT_ID, i.AGENT_ID;