USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE VIEW AGENT_INCIDENT_PRIORITY AS
SELECT
    i.EVENT_ID,
    i.AGENT_RUN_ID,
    i.AGENT_ID,
    i.EVENT_TS,
    i.ISSUE_TYPE,
    i.SEVERITY,
    i.ROOT_CAUSE,
    i.NEXT_STEP,
    i.AUTO_REMEDIATE,
    i.CONFIDENCE,
    i.INCIDENT_LABEL,
    COALESCE(d.DIRECTLY_IMPACTED_AGENTS, 0) AS DIRECTLY_IMPACTED_AGENTS,

    CASE
        WHEN i.SEVERITY = 'HIGH' THEN 50
        WHEN i.SEVERITY = 'MEDIUM' THEN 30
        ELSE 10
    END
    +
    CASE
        WHEN i.ISSUE_TYPE = 'PERMISSION' THEN 20
        WHEN i.ISSUE_TYPE = 'DATA_QUALITY' THEN 18
        WHEN i.ISSUE_TYPE = 'UPSTREAM' THEN 15
        WHEN i.ISSUE_TYPE = 'TIMEOUT' THEN 10
        ELSE 0
    END
    +
    (COALESCE(d.DIRECTLY_IMPACTED_AGENTS, 0) * 10)
    +
    CASE
        WHEN i.AUTO_REMEDIATE = 'NO' THEN 10
        ELSE 0
    END
    AS PRIORITY_SCORE

FROM AGENT_INCIDENTS_PARSED i
LEFT JOIN AGENT_DIRECT_IMPACT d
    ON i.EVENT_ID = d.EVENT_ID
WHERE i.ISSUE_TYPE <> 'SUCCESS';