USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT
    EVENT_ID,
    AGENT_ID,
    ISSUE_TYPE,
    SEVERITY,
    DIRECTLY_IMPACTED_AGENTS,
    AUTO_REMEDIATE,
    PRIORITY_SCORE
FROM AGENT_INCIDENT_PRIORITY
ORDER BY PRIORITY_SCORE DESC, EVENT_TS DESC;