USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT * 
FROM CORTEX_LOG_LAB
ORDER BY ID;

SELECT 
    COUNT(*) AS TOTAL_LOGS,
    COUNT_IF(LOG_TEXT ILIKE '%failed%') AS FAILED_LOGS,
    COUNT_IF(LOG_TEXT ILIKE '%success%') AS SUCCESS_LOGS
FROM CORTEX_LOG_LAB;