USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE TABLE AGENT_EVENT_LOGS (
    EVENT_ID STRING,
    AGENT_RUN_ID STRING,
    AGENT_ID STRING,
    PARENT_AGENT_RUN_ID STRING,
    SESSION_ID STRING,
    EVENT_TS TIMESTAMP_NTZ,
    STATUS STRING,
    EVENT_TYPE STRING,
    EXEC_TIME_MS NUMBER,
    TOKENS_INPUT NUMBER,
    TOKENS_OUTPUT NUMBER,
    MODEL_NAME STRING,
    WAREHOUSE_NAME STRING,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    OBJECT_NAME STRING,
    OBJECT_TYPE STRING,
    USER_ROLE STRING,
    ERROR_CODE STRING,
    ERROR_MESSAGE STRING,
    RETRY_COUNT NUMBER,
    LOG_TEXT STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);