USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE TABLE AGENT_DEPENDENCIES (
    PARENT_AGENT_ID STRING,
    CHILD_AGENT_ID STRING,
    DEPENDENCY_TYPE STRING,
    CRITICALITY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);