USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

CREATE OR REPLACE TABLE AGENT_REGISTRY (
    AGENT_ID STRING,
    AGENT_NAME STRING,
    AGENT_DOMAIN STRING,
    AGENT_OWNER STRING,
    BUSINESS_CRITICALITY STRING,
    DEFAULT_MODEL STRING,
    ACTIVE_FLAG STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);