USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

INSERT INTO AGENT_EVENT_LOGS (
    EVENT_ID,
    AGENT_RUN_ID,
    AGENT_ID,
    PARENT_AGENT_RUN_ID,
    SESSION_ID,
    EVENT_TS,
    STATUS,
    EVENT_TYPE,
    EXEC_TIME_MS,
    TOKENS_INPUT,
    TOKENS_OUTPUT,
    MODEL_NAME,
    WAREHOUSE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    OBJECT_TYPE,
    USER_ROLE,
    ERROR_CODE,
    ERROR_MESSAGE,
    RETRY_COUNT,
    LOG_TEXT
)
VALUES
(
    'EVT001',
    'RUN001',
    'fraud_detector',
    NULL,
    'SES001',
    CURRENT_TIMESTAMP(),
    'FAILED',
    'EXECUTION',
    12400,
    920,
    210,
    'llama3.1-8b',
    'WH_XS',
    'SNOWWORK_LAB',
    'OBSERVABILITY',
    'CUSTOMER_TABLE',
    'TABLE',
    'AGENT_RUNTIME_ROLE',
    'TIMEOUT_001',
    'Query timeout while reading CUSTOMER_TABLE',
    1,
    'Agent fraud_detector failed after 12.4 seconds with timeout while querying CUSTOMER_TABLE.'
),
(
    'EVT002',
    'RUN002',
    'recommendation_agent',
    'RUN001',
    'SES001',
    DATEADD(MINUTE, -10, CURRENT_TIMESTAMP()),
    'SUCCESS',
    'EXECUTION',
    2100,
    450,
    130,
    'llama3.1-8b',
    'WH_XS',
    'SNOWWORK_LAB',
    'OBSERVABILITY',
    'PRODUCT_CATALOG',
    'TABLE',
    'AGENT_RUNTIME_ROLE',
    NULL,
    NULL,
    0,
    'Agent recommendation_agent completed successfully in 2.1 seconds using SALES_HISTORY and PRODUCT_CATALOG.'
),
(
    'EVT003',
    'RUN003',
    'customer_chatbot',
    NULL,
    'SES002',
    DATEADD(MINUTE, -15, CURRENT_TIMESTAMP()),
    'FAILED',
    'ACCESS',
    3100,
    380,
    95,
    'llama3.1-8b',
    'WH_XS',
    'SNOWWORK_LAB',
    'OBSERVABILITY',
    'ORDER_SUMMARY_VIEW',
    'VIEW',
    'AGENT_RUNTIME_ROLE',
    'PERM_403',
    'Permission denied on ORDER_SUMMARY_VIEW',
    0,
    'Agent customer_chatbot failed with permission denied error while calling ORDER_SUMMARY_VIEW.'
),
(
    'EVT004',
    'RUN004',
    'inventory_updater',
    NULL,
    'SES003',
    DATEADD(MINUTE, -20, CURRENT_TIMESTAMP()),
    'FAILED',
    'DATA_READ',
    4500,
    510,
    150,
    'llama3.1-8b',
    'WH_XS',
    'SNOWWORK_LAB',
    'OBSERVABILITY',
    'SUPPLY_CHAIN_FEED',
    'TABLE',
    'AGENT_RUNTIME_ROLE',
    'DQ_100',
    'Null value violation in SUPPLY_CHAIN_FEED',
    3,
    'Agent inventory_updater retried 3 times and failed due to null value in SUPPLY_CHAIN_FEED.'
),
(
    'EVT005',
    'RUN005',
    'customer_profile_agent',
    NULL,
    'SES004',
    DATEADD(MINUTE, -25, CURRENT_TIMESTAMP()),
    'SUCCESS',
    'EXECUTION',
    1800,
    300,
    80,
    'llama3.1-8b',
    'WH_XS',
    'SNOWWORK_LAB',
    'OBSERVABILITY',
    'CUSTOMER_PROFILE_VIEW',
    'VIEW',
    'AGENT_RUNTIME_ROLE',
    NULL,
    NULL,
    0,
    'Agent customer_profile_agent completed successfully and refreshed customer profile context.'
),
(
    'EVT006',
    'RUN006',
    'fraud_score_writer',
    'RUN001',
    'SES001',
    DATEADD(MINUTE, -5, CURRENT_TIMESTAMP()),
    'FAILED',
    'WRITE',
    5200,
    610,
    170,
    'llama3.1-8b',
    'WH_XS',
    'SNOWWORK_LAB',
    'OBSERVABILITY',
    'FRAUD_SCORE_TABLE',
    'TABLE',
    'AGENT_RUNTIME_ROLE',
    'UPSTREAM_FAIL',
    'Upstream dependency unavailable',
    1,
    'Agent fraud_score_writer failed because upstream fraud_detector output was unavailable.'
);