USE DATABASE SNOWWORK_LAB;
USE SCHEMA OBSERVABILITY;

SELECT COUNT(*) AS AGENT_REGISTRY_COUNT
FROM AGENT_REGISTRY;

SELECT COUNT(*) AS AGENT_DEPENDENCIES_COUNT
FROM AGENT_DEPENDENCIES;

SELECT COUNT(*) AS AGENT_EVENT_LOGS_COUNT
FROM AGENT_EVENT_LOGS;

SELECT *
FROM AGENT_REGISTRY
ORDER BY AGENT_ID;

SELECT *
FROM AGENT_DEPENDENCIES
ORDER BY PARENT_AGENT_ID, CHILD_AGENT_ID;

SELECT
    EVENT_ID,
    AGENT_ID,
    STATUS,
    EVENT_TYPE,
    EXEC_TIME_MS,
    OBJECT_NAME,
    ERROR_CODE,
    RETRY_COUNT
FROM AGENT_EVENT_LOGS
ORDER BY EVENT_TS DESC;